---
- name: Create network
  community.docker.docker_network:
    name: "{{ network_name }}"
    driver: overlay

- name: Deploy services
  include: "../services/{{ item.name }}/service.yaml"
  vars:
    - service_name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"