---
- name: Create network
  community.docker.docker_network:
    name: {{ networkName }}"
    driver: overlay

- name: Deploy services
  include: "../services/{{ item }}/service.yaml"
  vars:
    - service_name: "{{ item }}"
  loop: "{{ services }}"