galaxy_info:
  role_name: Deploy
  description: Deploy microservers to Docker cluster
  license: MIT
  min_ansible_version: 2.9
  author: put the name here
  platforms:
    - name: Ubuntu
      versions:
        - all
