---
- name: "[{{ service_name }}]: secret configuration"
  include: "../secret.yaml"

- name: "[{{ service_name }}]: deploy service"
  block:
  - name: "[{{ service_name }}]: deploy service"
    community.docker.docker_swarm_service:
      name: "{{ service_name }}"
      image: "localhost:5000/{{ service_name }}:latest"
      state: present
      networks:
        name: "{{ networkName }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3002
          target_port: 3000
      secrets:
        - secret_name: "{{ service_name }}.env"
          filename: "/opt/app/.env"
  tags: "{{ service_name }}"
