---
- name: "[{{ service_name }}]: config configuration"
  include: "../config.yaml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: "{{ config_item }}"

- name: "[{{ service_name }}]: deploy nginx"
  block:
  - name: "[{{ service_name }}]: deploy nginx"
    community.docker.docker_swarm_service:
      name: "{{ service_name }}"
      image: "nginx:{{ version }}"  # `version` var will be available because it is set up in deploy/tasks/main.yaml
      state: present
      networks:
        name: "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 80
          target_port: 80
      configs:
        - config_name: nginx.conf
          filename: "/etc/nginx/nginx.conf"
  tags: "{{ service_name }}"
