galaxy_info:
  role_name: Swarm-join
  description: Swarm cluster joining
  license: MIT
  min_ansible_version: 2.9
  author: put the name here
  platforms:
    - name: Ubuntu
      versions:
        - all
