---
- name: Init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Directory existence
  local_action:
    module: file
    path: ./tokens
    state: directory

- name: Store manager token
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"

- name: Store worker token
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
