---
- name: Init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: Directory existence
  file:
    path: ./tokens
    state: directory
    mode: '0777'
  delegate_to: localhost
  notify: Test  # handler name

- name: Store manager token
  copy:
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"
    mode: '0644'
  delegate_to: localhost

- name: Store worker token
  copy:
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"
    mode: '0644'
  delegate_to: localhost
